// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface _CallbackSenderOperations
{
    void initiateCallback(CallbackReceiverPrx proxy, Ice.Current __current);

    void shutdown(Ice.Current __current);
}
