// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface CallbackReceiverPrx extends Ice.ObjectPrx
{
    public void callback();

    public void callback(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_callback();

    public Ice.AsyncResult begin_callback(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_callback(Ice.Callback __cb);

    public Ice.AsyncResult begin_callback(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_callback(Callback_CallbackReceiver_callback __cb);

    public Ice.AsyncResult begin_callback(java.util.Map<String, String> __ctx, Callback_CallbackReceiver_callback __cb);

    public void end_callback(Ice.AsyncResult __result);
}
