// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public final class CallbackReceiverPrxHelper extends Ice.ObjectPrxHelperBase implements CallbackReceiverPrx
{
    private static final String __callback_name = "callback";

    public void callback()
    {
        callback(null, false);
    }

    public void callback(java.util.Map<String, String> __ctx)
    {
        callback(__ctx, true);
    }

    private void callback(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "callback", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _CallbackReceiverDel __del = (_CallbackReceiverDel)__delBase;
                    __del.callback(__ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_callback()
    {
        return begin_callback(null, false, null);
    }

    public Ice.AsyncResult begin_callback(java.util.Map<String, String> __ctx)
    {
        return begin_callback(__ctx, true, null);
    }

    public Ice.AsyncResult begin_callback(Ice.Callback __cb)
    {
        return begin_callback(null, false, __cb);
    }

    public Ice.AsyncResult begin_callback(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_callback(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_callback(Callback_CallbackReceiver_callback __cb)
    {
        return begin_callback(null, false, __cb);
    }

    public Ice.AsyncResult begin_callback(java.util.Map<String, String> __ctx, Callback_CallbackReceiver_callback __cb)
    {
        return begin_callback(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_callback(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __callback_name, __cb);
        try
        {
            __result.__prepare(__callback_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_callback(Ice.AsyncResult __result)
    {
        __end(__result, __callback_name);
    }

    public static CallbackReceiverPrx checkedCast(Ice.ObjectPrx __obj)
    {
        CallbackReceiverPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof CallbackReceiverPrx)
            {
                __d = (CallbackReceiverPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    CallbackReceiverPrxHelper __h = new CallbackReceiverPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static CallbackReceiverPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        CallbackReceiverPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof CallbackReceiverPrx)
            {
                __d = (CallbackReceiverPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    CallbackReceiverPrxHelper __h = new CallbackReceiverPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static CallbackReceiverPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        CallbackReceiverPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    CallbackReceiverPrxHelper __h = new CallbackReceiverPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static CallbackReceiverPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        CallbackReceiverPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    CallbackReceiverPrxHelper __h = new CallbackReceiverPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static CallbackReceiverPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        CallbackReceiverPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof CallbackReceiverPrx)
            {
                __d = (CallbackReceiverPrx)__obj;
            }
            else
            {
                CallbackReceiverPrxHelper __h = new CallbackReceiverPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static CallbackReceiverPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        CallbackReceiverPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            CallbackReceiverPrxHelper __h = new CallbackReceiverPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Demo::CallbackReceiver",
        "::Ice::Object"
    };

    public static String ice_staticId()
    {
        return __ids[0];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _CallbackReceiverDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _CallbackReceiverDelD();
    }

    public static void __write(IceInternal.BasicStream __os, CallbackReceiverPrx v)
    {
        __os.writeProxy(v);
    }

    public static CallbackReceiverPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            CallbackReceiverPrxHelper result = new CallbackReceiverPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
