// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface CallbackSenderPrx extends Ice.ObjectPrx
{
    public void initiateCallback(CallbackReceiverPrx proxy);

    public void initiateCallback(CallbackReceiverPrx proxy, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_initiateCallback(CallbackReceiverPrx proxy);

    public Ice.AsyncResult begin_initiateCallback(CallbackReceiverPrx proxy, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_initiateCallback(CallbackReceiverPrx proxy, Ice.Callback __cb);

    public Ice.AsyncResult begin_initiateCallback(CallbackReceiverPrx proxy, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_initiateCallback(CallbackReceiverPrx proxy, Callback_CallbackSender_initiateCallback __cb);

    public Ice.AsyncResult begin_initiateCallback(CallbackReceiverPrx proxy, java.util.Map<String, String> __ctx, Callback_CallbackSender_initiateCallback __cb);

    public void end_initiateCallback(Ice.AsyncResult __result);

    public void shutdown();

    public void shutdown(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_shutdown();

    public Ice.AsyncResult begin_shutdown(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_shutdown(Ice.Callback __cb);

    public Ice.AsyncResult begin_shutdown(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_shutdown(Callback_CallbackSender_shutdown __cb);

    public Ice.AsyncResult begin_shutdown(java.util.Map<String, String> __ctx, Callback_CallbackSender_shutdown __cb);

    public void end_shutdown(Ice.AsyncResult __result);
}
