// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface CallbackReceiver extends Ice.Object,
                                          _CallbackReceiverOperations, _CallbackReceiverOperationsNC
{
    public static final long serialVersionUID = -1575754802L;
}
